use phf::phf_map;
use std::fmt;

/// Error returned when a glyph name is not found
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownGlyph(pub String);

impl fmt::Display for UnknownGlyph {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Unknown glyph: '{}'", self.0)
    }
}

impl std::error::Error for UnknownGlyph {}

/// Perfect hash map of glyph names to Unicode characters (with VS15 applied)
///
/// All 531 glyphs have VS15 (U+FE0E) variation selector appended for consistent
/// text rendering across platforms.
static GLYPHS: phf::Map<&'static str, &'static str> = phf_map! {
    "dot" => "·︎",
    "bullet" => "•︎",
    "dash" => "─︎",
    "bolddash" => "━︎",
    "arrow" => "→︎",
    "star" => "★︎",
    "diamond" => "◆︎",
    "pipe" => "|︎",
    "tilde" => "~︎",
    "block.full" => "█︎",
    "block.upper.1" => "▔︎",
    "block.upper.4" => "▀︎",
    "block.lower.1" => "▁︎",
    "block.lower.2" => "▂︎",
    "block.lower.3" => "▃︎",
    "block.lower.4" => "▄︎",
    "block.lower.5" => "▅︎",
    "block.lower.6" => "▆︎",
    "block.lower.7" => "▇︎",
    "block.left.1" => "▏︎",
    "block.left.2" => "▎︎",
    "block.left.3" => "▍︎",
    "block.left.4" => "▌︎",
    "block.left.5" => "▋︎",
    "block.left.6" => "▊︎",
    "block.left.7" => "▉︎",
    "block.right.1" => "▕︎",
    "block.right.4" => "▐︎",
    "shade.light" => "░︎",
    "shade.medium" => "▒︎",
    "shade.dark" => "▓︎",
    "quad.1" => "▘︎",
    "quad.2" => "▝︎",
    "quad.3" => "▖︎",
    "quad.4" => "▗︎",
    "quad.1-4" => "▚︎",
    "quad.2-3" => "▞︎",
    "quad.1-3-4" => "▙︎",
    "quad.1-2-3" => "▛︎",
    "quad.1-2-4" => "▜︎",
    "quad.2-3-4" => "▟︎",
    "braille.empty" => "⠀︎",
    "braille.bar.1" => "⡀︎",
    "braille.bar.2" => "⡄︎",
    "braille.bar.3" => "⡆︎",
    "braille.bar.4" => "⡇︎",
    "braille.bar.5" => "⣇︎",
    "braille.bar.6" => "⣧︎",
    "braille.bar.7" => "⣷︎",
    "braille.bar.8" => "⣿︎",
    "braille.full" => "⣿︎",
    "braille.left" => "⡇︎",
    "braille.right" => "⢸︎",
    "box.light.h" => "─︎",
    "box.light.v" => "│︎",
    "box.light.tl" => "┌︎",
    "box.light.tr" => "┐︎",
    "box.light.bl" => "└︎",
    "box.light.br" => "┘︎",
    "box.light.cross" => "┼︎",
    "box.light.t-down" => "┬︎",
    "box.light.t-up" => "┴︎",
    "box.light.t-right" => "├︎",
    "box.light.t-left" => "┤︎",
    "box.heavy.h" => "━︎",
    "box.heavy.v" => "┃︎",
    "box.heavy.tl" => "┏︎",
    "box.heavy.tr" => "┓︎",
    "box.heavy.bl" => "┗︎",
    "box.heavy.br" => "┛︎",
    "box.heavy.cross" => "╋︎",
    "box.heavy.t-down" => "┳︎",
    "box.heavy.t-up" => "┻︎",
    "box.heavy.t-right" => "┣︎",
    "box.heavy.t-left" => "┫︎",
    "box.double.h" => "═︎",
    "box.double.v" => "║︎",
    "box.double.tl" => "╔︎",
    "box.double.tr" => "╗︎",
    "box.double.bl" => "╚︎",
    "box.double.br" => "╝︎",
    "box.double.cross" => "╬︎",
    "box.double.t-down" => "╦︎",
    "box.double.t-up" => "╩︎",
    "box.double.t-right" => "╠︎",
    "box.double.t-left" => "╣︎",
    "box.round.tl" => "╭︎",
    "box.round.tr" => "╮︎",
    "box.round.bl" => "╰︎",
    "box.round.br" => "╯︎",
    "circle.0" => "⓪︎",
    "circle.1" => "①︎",
    "circle.2" => "②︎",
    "circle.3" => "③︎",
    "circle.4" => "④︎",
    "circle.5" => "⑤︎",
    "circle.6" => "⑥︎",
    "circle.7" => "⑦︎",
    "circle.8" => "⑧︎",
    "circle.9" => "⑨︎",
    "circle.10" => "⑩︎",
    "circle.11" => "⑪︎",
    "circle.12" => "⑫︎",
    "circle.13" => "⑬︎",
    "circle.14" => "⑭︎",
    "circle.15" => "⑮︎",
    "circle.16" => "⑯︎",
    "circle.17" => "⑰︎",
    "circle.18" => "⑱︎",
    "circle.19" => "⑲︎",
    "circle.20" => "⑳︎",
    "neg-circle.0" => "⓿︎",
    "neg-circle.1" => "❶︎",
    "neg-circle.2" => "❷︎",
    "neg-circle.3" => "❸︎",
    "neg-circle.4" => "❹︎",
    "neg-circle.5" => "❺︎",
    "neg-circle.6" => "❻︎",
    "neg-circle.7" => "❼︎",
    "neg-circle.8" => "❽︎",
    "neg-circle.9" => "❾︎",
    "neg-circle.10" => "❿︎",
    "neg-circle.11" => "⓫︎",
    "neg-circle.12" => "⓬︎",
    "neg-circle.13" => "⓭︎",
    "neg-circle.14" => "⓮︎",
    "neg-circle.15" => "⓯︎",
    "neg-circle.16" => "⓰︎",
    "neg-circle.17" => "⓱︎",
    "neg-circle.18" => "⓲︎",
    "neg-circle.19" => "⓳︎",
    "neg-circle.20" => "⓴︎",
    "dbl-circle.1" => "⓵︎",
    "dbl-circle.2" => "⓶︎",
    "dbl-circle.3" => "⓷︎",
    "dbl-circle.4" => "⓸︎",
    "dbl-circle.5" => "⓹︎",
    "dbl-circle.6" => "⓺︎",
    "dbl-circle.7" => "⓻︎",
    "dbl-circle.8" => "⓼︎",
    "dbl-circle.9" => "⓽︎",
    "dbl-circle.10" => "⓾︎",
    "paren.1" => "⑴︎",
    "paren.2" => "⑵︎",
    "paren.3" => "⑶︎",
    "paren.4" => "⑷︎",
    "paren.5" => "⑸︎",
    "paren.6" => "⑹︎",
    "paren.7" => "⑺︎",
    "paren.8" => "⑻︎",
    "paren.9" => "⑼︎",
    "paren.10" => "⑽︎",
    "paren.11" => "⑾︎",
    "paren.12" => "⑿︎",
    "paren.13" => "⒀︎",
    "paren.14" => "⒁︎",
    "paren.15" => "⒂︎",
    "paren.16" => "⒃︎",
    "paren.17" => "⒄︎",
    "paren.18" => "⒅︎",
    "paren.19" => "⒆︎",
    "paren.20" => "⒇︎",
    "paren.a" => "⒜︎",
    "paren.b" => "⒝︎",
    "paren.c" => "⒞︎",
    "paren.d" => "⒟︎",
    "paren.e" => "⒠︎",
    "paren.f" => "⒡︎",
    "paren.g" => "⒢︎",
    "paren.h" => "⒣︎",
    "paren.i" => "⒤︎",
    "paren.j" => "⒥︎",
    "paren.k" => "⒦︎",
    "paren.l" => "⒧︎",
    "paren.m" => "⒨︎",
    "paren.n" => "⒩︎",
    "paren.o" => "⒪︎",
    "paren.p" => "⒫︎",
    "paren.q" => "⒬︎",
    "paren.r" => "⒭︎",
    "paren.s" => "⒮︎",
    "paren.t" => "⒯︎",
    "paren.u" => "⒰︎",
    "paren.v" => "⒱︎",
    "paren.w" => "⒲︎",
    "paren.x" => "⒳︎",
    "paren.y" => "⒴︎",
    "paren.z" => "⒵︎",
    "period.0" => "🄀︎",
    "period.1" => "⒈︎",
    "period.2" => "⒉︎",
    "period.3" => "⒊︎",
    "period.4" => "⒋︎",
    "period.5" => "⒌︎",
    "period.6" => "⒍︎",
    "period.7" => "⒎︎",
    "period.8" => "⒏︎",
    "period.9" => "⒐︎",
    "period.10" => "⒑︎",
    "period.11" => "⒒︎",
    "period.12" => "⒓︎",
    "period.13" => "⒔︎",
    "period.14" => "⒕︎",
    "period.15" => "⒖︎",
    "period.16" => "⒗︎",
    "period.17" => "⒘︎",
    "period.18" => "⒙︎",
    "period.19" => "⒚︎",
    "period.20" => "⒛︎",
    "square.filled" => "■︎",
    "square.empty" => "□︎",
    "square.rounded" => "▢︎",
    "square.dotted" => "▣︎",
    "square.h-lines" => "▤︎",
    "square.v-lines" => "▥︎",
    "square.grid" => "▦︎",
    "square.diag-down" => "▧︎",
    "square.diag-up" => "▨︎",
    "square.cross" => "▩︎",
    "circle.filled" => "●︎",
    "circle.empty" => "○︎",
    "circle.dotted" => "◌︎",
    "circle.target" => "◎︎",
    "circle.half-left" => "◐︎",
    "circle.half-right" => "◑︎",
    "circle.half-bottom" => "◒︎",
    "circle.half-top" => "◓︎",
    "circle.quarter-tl" => "◔︎",
    "circle.quarter-tr" => "◕︎",
    "circle.left-half-filled" => "◖︎",
    "circle.right-half-filled" => "◗︎",
    "circle.large" => "⬤︎",
    "circle.medium-filled" => "⚫︎",
    "circle.medium-empty" => "⚪︎",
    "tri.up" => "▲︎",
    "tri.up.empty" => "△︎",
    "tri.up.small" => "▴︎",
    "tri.up.small.empty" => "▵︎",
    "tri.right" => "▶︎",
    "tri.right.empty" => "▷︎",
    "tri.right.small" => "▸︎",
    "tri.right.small.empty" => "▹︎",
    "tri.right.pointer" => "►︎",
    "tri.right.pointer.empty" => "▻︎",
    "tri.down" => "▼︎",
    "tri.down.empty" => "▽︎",
    "tri.down.small" => "▾︎",
    "tri.down.small.empty" => "▿︎",
    "tri.left" => "◀︎",
    "tri.left.empty" => "◁︎",
    "tri.left.small" => "◂︎",
    "tri.left.small.empty" => "◃︎",
    "tri.left.pointer" => "◄︎",
    "tri.left.pointer.empty" => "◅︎",
    "diamond.filled" => "◆︎",
    "diamond.empty" => "◇︎",
    "diamond.dot" => "◈︎",
    "diamond.lozenge" => "◊︎",
    "check.empty" => "☐︎",
    "check.yes" => "☑︎",
    "check.no" => "☒︎",
    "check.mark" => "✓︎",
    "check.heavy" => "✔︎",
    "check.x" => "✗︎",
    "check.x.heavy" => "✘︎",
    "arrow.left" => "←︎",
    "arrow.up" => "↑︎",
    "arrow.right" => "→︎",
    "arrow.down" => "↓︎",
    "arrow.left-right" => "↔︎",
    "arrow.up-down" => "↕︎",
    "arrow.nw" => "↖︎",
    "arrow.ne" => "↗︎",
    "arrow.se" => "↘︎",
    "arrow.sw" => "↙︎",
    "arrow.double-left" => "⇐︎",
    "arrow.double-up" => "⇑︎",
    "arrow.double-right" => "⇒︎",
    "arrow.double-down" => "⇓︎",
    "arrow.double-h" => "⇔︎",
    "arrow.double-v" => "⇕︎",
    "arrow.dashed-right" => "⇢︎",
    "arrow.dashed-left" => "⇠︎",
    "arrow.dashed-up" => "⇡︎",
    "arrow.dashed-down" => "⇣︎",
    "die.1" => "⚀︎",
    "die.2" => "⚁︎",
    "die.3" => "⚂︎",
    "die.4" => "⚃︎",
    "die.5" => "⚄︎",
    "die.6" => "⚅︎",
    "card.spade" => "♠︎",
    "card.spade.empty" => "♤︎",
    "card.heart" => "♥︎",
    "card.heart.empty" => "♡︎",
    "card.diamond" => "♦︎",
    "card.diamond.empty" => "♢︎",
    "card.club" => "♣︎",
    "card.club.empty" => "♧︎",
    "music.quarter" => "♩︎",
    "music.eighth" => "♪︎",
    "music.beamed" => "♫︎",
    "music.beamed-16" => "♬︎",
    "music.flat" => "♭︎",
    "music.natural" => "♮︎",
    "music.sharp" => "♯︎",
    "math.infinity" => "∞︎",
    "math.approx" => "≈︎",
    "math.not-equal" => "≠︎",
    "math.lte" => "≤︎",
    "math.gte" => "≥︎",
    "math.plus-minus" => "±︎",
    "math.times" => "×︎",
    "math.divide" => "÷︎",
    "math.sqrt" => "√︎",
    "math.sum" => "∑︎",
    "math.product" => "∏︎",
    "math.integral" => "∫︎",
    "math.partial" => "∂︎",
    "math.delta" => "∆︎",
    "math.nabla" => "∇︎",
    "math.element-of" => "∈︎",
    "math.not-element" => "∉︎",
    "math.subset" => "⊂︎",
    "math.superset" => "⊃︎",
    "math.union" => "∪︎",
    "math.intersect" => "∩︎",
    "math.empty-set" => "∅︎",
    "math.forall" => "∀︎",
    "math.exists" => "∃︎",
    "math.not" => "¬︎",
    "math.and" => "∧︎",
    "math.or" => "∨︎",
    "math.xor" => "⊕︎",
    "math.therefore" => "∴︎",
    "math.because" => "∵︎",
    "sup.0" => "⁰︎",
    "sup.1" => "¹︎",
    "sup.2" => "²︎",
    "sup.3" => "³︎",
    "sup.4" => "⁴︎",
    "sup.5" => "⁵︎",
    "sup.6" => "⁶︎",
    "sup.7" => "⁷︎",
    "sup.8" => "⁸︎",
    "sup.9" => "⁹︎",
    "sup.+" => "⁺︎",
    "sup.-" => "⁻︎",
    "sup.=" => "⁼︎",
    "sup.(" => "⁽︎",
    "sup.)" => "⁾︎",
    "sup.n" => "ⁿ︎",
    "sub.0" => "₀︎",
    "sub.1" => "₁︎",
    "sub.2" => "₂︎",
    "sub.3" => "₃︎",
    "sub.4" => "₄︎",
    "sub.5" => "₅︎",
    "sub.6" => "₆︎",
    "sub.7" => "₇︎",
    "sub.8" => "₈︎",
    "sub.9" => "₉︎",
    "sub.+" => "₊︎",
    "sub.-" => "₋︎",
    "sub.=" => "₌︎",
    "sub.(" => "₍︎",
    "sub.)" => "₎︎",
    "roman.1" => "Ⅰ︎",
    "roman.2" => "Ⅱ︎",
    "roman.3" => "Ⅲ︎",
    "roman.4" => "Ⅳ︎",
    "roman.5" => "Ⅴ︎",
    "roman.6" => "Ⅵ︎",
    "roman.7" => "Ⅶ︎",
    "roman.8" => "Ⅷ︎",
    "roman.9" => "Ⅸ︎",
    "roman.10" => "Ⅹ︎",
    "roman.11" => "Ⅺ︎",
    "roman.12" => "Ⅻ︎",
    "roman.50" => "Ⅼ︎",
    "roman.100" => "Ⅽ︎",
    "roman.500" => "Ⅾ︎",
    "roman.1000" => "Ⅿ︎",
    "star.filled" => "★︎",
    "star.empty" => "☆︎",
    "star.4" => "✦︎",
    "star.4.empty" => "✧︎",
    "star.circle" => "✪︎",
    "star.shadow" => "✫︎",
    "star.circle.empty" => "✬︎",
    "star.5.empty" => "✭︎",
    "star.outlined" => "✮︎",
    "star.pinwheel" => "✯︎",
    "star.heavy" => "✰︎",
    "star.6" => "✡︎",
    "star.8" => "✴︎",
    "star.sparkle" => "❇︎",
    "currency.dollar" => "$︎",
    "currency.cent" => "¢︎",
    "currency.pound" => "£︎",
    "currency.yen" => "¥︎",
    "currency.euro" => "€︎",
    "currency.won" => "₩︎",
    "currency.rupee" => "₹︎",
    "currency.ruble" => "₽︎",
    "currency.bitcoin" => "₿︎",
    "currency.generic" => "¤︎",
    "greek.alpha" => "α︎",
    "greek.beta" => "β︎",
    "greek.gamma" => "γ︎",
    "greek.delta" => "δ︎",
    "greek.epsilon" => "ε︎",
    "greek.zeta" => "ζ︎",
    "greek.eta" => "η︎",
    "greek.theta" => "θ︎",
    "greek.iota" => "ι︎",
    "greek.kappa" => "κ︎",
    "greek.lambda" => "λ︎",
    "greek.mu" => "μ︎",
    "greek.nu" => "ν︎",
    "greek.xi" => "ξ︎",
    "greek.omicron" => "ο︎",
    "greek.pi" => "π︎",
    "greek.rho" => "ρ︎",
    "greek.sigma" => "σ︎",
    "greek.tau" => "τ︎",
    "greek.upsilon" => "υ︎",
    "greek.phi" => "φ︎",
    "greek.chi" => "χ︎",
    "greek.psi" => "ψ︎",
    "greek.omega" => "ω︎",
    "greek.Alpha" => "Α︎",
    "greek.Beta" => "Β︎",
    "greek.Gamma" => "Γ︎",
    "greek.Delta" => "Δ︎",
    "greek.Epsilon" => "Ε︎",
    "greek.Zeta" => "Ζ︎",
    "greek.Eta" => "Η︎",
    "greek.Theta" => "Θ︎",
    "greek.Iota" => "Ι︎",
    "greek.Kappa" => "Κ︎",
    "greek.Lambda" => "Λ︎",
    "greek.Mu" => "Μ︎",
    "greek.Nu" => "Ν︎",
    "greek.Xi" => "Ξ︎",
    "greek.Omicron" => "Ο︎",
    "greek.Pi" => "Π︎",
    "greek.Rho" => "Ρ︎",
    "greek.Sigma" => "Σ︎",
    "greek.Tau" => "Τ︎",
    "greek.Upsilon" => "Υ︎",
    "greek.Phi" => "Φ︎",
    "greek.Chi" => "Χ︎",
    "greek.Psi" => "Ψ︎",
    "greek.Omega" => "Ω︎",
    "frac.1-4" => "¼︎",
    "frac.1-2" => "½︎",
    "frac.3-4" => "¾︎",
    "frac.1-7" => "⅐︎",
    "frac.1-9" => "⅑︎",
    "frac.1-10" => "⅒︎",
    "frac.1-3" => "⅓︎",
    "frac.2-3" => "⅔︎",
    "frac.1-5" => "⅕︎",
    "frac.2-5" => "⅖︎",
    "frac.3-5" => "⅗︎",
    "frac.4-5" => "⅘︎",
    "frac.1-6" => "⅙︎",
    "frac.5-6" => "⅚︎",
    "frac.1-8" => "⅛︎",
    "frac.3-8" => "⅜︎",
    "frac.5-8" => "⅝︎",
    "frac.7-8" => "⅞︎",
    "misc.skull" => "☠︎",
    "misc.radioactive" => "☢︎",
    "misc.biohazard" => "☣︎",
    "misc.peace" => "☮︎",
    "misc.yinyang" => "☯︎",
    "misc.smiley" => "☺︎",
    "misc.frown" => "☹︎",
    "misc.sun" => "☀︎",
    "misc.cloud" => "☁︎",
    "misc.umbrella" => "☂︎",
    "misc.snowman" => "☃︎",
    "misc.comet" => "☄︎",
    "misc.lightning" => "⚡︎",
    "misc.anchor" => "⚓︎",
    "misc.crossed-swords" => "⚔︎",
    "misc.scales" => "⚖︎",
    "misc.gear" => "⚙︎",
    "misc.atom" => "⚛︎",
    "misc.fleur-de-lis" => "⚜︎",
    "misc.warning" => "⚠︎",
    "misc.recycle" => "♻︎",
    "misc.wheelchair" => "♿︎",
    "misc.medical" => "⚕︎",
    "misc.infinity" => "♾︎",
    "misc.hot" => "♨︎",
    "misc.phone" => "☎︎",
    "misc.mail" => "✉︎",
    "misc.scissors" => "✂︎",
    "misc.pencil" => "✏︎",
    "misc.flag" => "⚑︎",
    "misc.flag.empty" => "⚐︎",
    "key.command" => "⌘︎",
    "key.option" => "⌥︎",
    "key.control" => "⌃︎",
    "key.shift" => "⇧︎",
    "key.caps" => "⇪︎",
    "key.return" => "⏎︎",
    "key.delete" => "⌫︎",
    "key.forward-delete" => "⌦︎",
    "key.tab" => "⇥︎",
    "key.backtab" => "⇤︎",
    "key.escape" => "⎋︎",
    "key.space" => "␣︎",
    "key.eject" => "⏏︎",
    "key.power" => "⏻︎",
    "key.enter" => "⌅︎",
    "chess.king.white" => "♔︎",
    "chess.queen.white" => "♕︎",
    "chess.rook.white" => "♖︎",
    "chess.bishop.white" => "♗︎",
    "chess.knight.white" => "♘︎",
    "chess.pawn.white" => "♙︎",
    "chess.king.black" => "♚︎",
    "chess.queen.black" => "♛︎",
    "chess.rook.black" => "♜︎",
    "chess.bishop.black" => "♝︎",
    "chess.knight.black" => "♞︎",
    "chess.pawn.black" => "♟︎",
};

/// Look up a glyph by name
///
/// Returns the Unicode character(s) for the given glyph name, with VS15 variation
/// selector applied for text rendering.
///
/// # Examples
///
/// ```
/// use prettychars::glyph;
///
/// assert_eq!(glyph("star.filled").unwrap(), "★︎");
/// assert_eq!(glyph("arrow.double-right").unwrap(), "⇒︎");
/// assert_eq!(glyph("check.mark").unwrap(), "✓︎");
/// ```
///
/// # Errors
///
/// Returns [`UnknownGlyph`] if the name doesn't exist:
///
/// ```
/// use prettychars::{glyph, UnknownGlyph};
///
/// assert_eq!(glyph("does-not-exist"), Err(UnknownGlyph("does-not-exist".to_string())));
/// ```
pub fn glyph(name: &str) -> Result<&'static str, UnknownGlyph> {
    GLYPHS
        .get(name)
        .copied()
        .ok_or_else(|| UnknownGlyph(name.to_string()))
}

/// Iterator over all available glyph names
///
/// Useful for discovery, documentation, and testing.
///
/// # Examples
///
/// ```
/// use prettychars::glyph_names;
///
/// // Find all arrow glyphs
/// for name in glyph_names().filter(|n| n.starts_with("arrow.")) {
///     println!("{}", name);
/// }
/// ```
pub fn glyph_names() -> impl Iterator<Item = &'static str> {
    GLYPHS.keys().copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_glyph_lookup() {
        assert!(glyph("star").is_ok());
        assert!(glyph("arrow").is_ok());
        assert!(glyph("check.mark").is_ok());
    }

    #[test]
    fn test_unknown_glyph() {
        assert_eq!(
            glyph("does-not-exist"),
            Err(UnknownGlyph("does-not-exist".to_string()))
        );
    }

    #[test]
    fn test_glyph_count() {
        assert_eq!(glyph_names().count(), 531);
    }

    #[test]
    fn test_vs15_applied() {
        let star = glyph("star.filled").unwrap();
        assert!(star.contains('\u{FE0E}'));
    }
}
